import {StyleSheet} from 'react-native';
import { heightRatio } from '../../utils/styleSheetGuide';

const styles = StyleSheet.create({
  reform: {
    paddingTop: heightRatio*30,
    alignSelf: 'stretch',
    flex: 1,
  },
  textPress: {
    color: 'black',
    fontWeight: 'bold',
    fontStyle: 'italic',
  },
  textt: {
    color: 'grey',
    fontWeight: '200',
  },
  toggle: {
    marginBottom: heightRatio*40,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  toggletxtactive: {
    marginHorizontal: 15,
    borderBottomColor: '#000000',
    paddingBottom: 4,
    borderBottomWidth: 2,
  },
  toggletxtinactive: {
    marginHorizontal: 15,
    borderBottomColor: '#E3EEF7',
    paddingBottom: 4,
    borderBottomWidth: 2,
  },

  toggletxtact: {
    marginHorizontal: 15,
    borderBottomColor: '#E3EEF7',
    paddingBottom: 4,
    borderBottomWidth: 2,
  },
  toggletxtinact: {
    marginHorizontal: 15,
    borderBottomColor: '#fff',
    paddingBottom: 4,
    borderBottomWidth: 2,
  },

  header: {
    alignSelf: 'center',
    fontWeight: 'bold',
    fontSize: 24,
    color: '#000000',
    paddingBottom: heightRatio*10,
    borderBottomColor: 1,
  },
  subheader: {
    alignSelf: 'center',
    color:"#22304A"
  },
  subheader1: {
    alignSelf: 'center',
    paddingBottom: heightRatio*60,
    color:"#22304A"
  },
  searchIcon: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  searchIconTick: {
    // alignContent: 'center',
    height: '100%',
    width:"100%",
    justifyContent: 'center',
    alignItems: 'center',
     paddingTop: 8,
     paddingHorizontal:10,
    backgroundColor: '#F18F49',
  },
  phoneno: {
    borderColor: '#AFB8C4',
    borderWidth: 0.5,
    height: heightRatio*35,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent:"center",
    backgroundColor: '#E3EEF7',
    // marginBottom: 180,
    marginLeft: 30,
    marginRight: 30,
    marginBottom: heightRatio*24,
    borderBottomColor: '#FFF',
    borderRightColor: '#FFF',
  },
  password: {
    borderColor: '#AFB8C4',
    borderWidth: 0.5,
    height: heightRatio*35,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E3EEF7',
    // marginBottom: 180,
    marginLeft: 30,
    marginRight: 30,
    marginBottom: heightRatio*24,
    borderBottomColor: '#FFF',
    borderRightColor: '#FFF',
  },
  setpassword: {
    borderColor: '#AFB8C4',
    borderWidth: 0.5,
    height: heightRatio*35,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E3EEF7',
    // marginTop: 10,
    marginLeft: 30,
    marginRight: 30,
    elevation: -4,
    marginBottom: heightRatio*24,
    borderBottomColor: '#FFF',
    borderRightColor: '#FFF',
  },
  otpset: {
    flexDirection: 'row',
    alignSelf: 'stretch',
    marginLeft: 30,
    marginRight: 30,
    marginBottom: heightRatio*24,
    borderBottomColor: '#FFF',
    borderRightColor: '#FFF',
  },
  otp: {
    flex: 1,
    borderColor: '#AFB8C4',
    borderWidth: 0.5,
    height: heightRatio*35,
    flexDirection: 'row',
    backgroundColor: '#E3EEF7', justifyContent:"flex-start",alignItems:"center"
  },
  otptextinput: {
    flex:1
  },
  textinput: {
    justifyContent: 'flex-start',
    flex: 1,
    alignSelf: 'stretch',
    color: '#000',
    fontWeight:"normal"
  },
  otpverify: {
    marginLeft: 10,
    // flex:1,
    alignSelf: 'stretch',
    padding: 10,
    alignItems: 'center',
    backgroundColor: '#F18F49',
    justifyContent: 'center',
    paddingHorizontal: 40,
    borderRadius: 5,
  },
  margintothebottom: {
    // marginBottom: 20,
  },
  button: {
    height: heightRatio*35,
    alignSelf: 'stretch',
    alignItems: 'center',
    // padding: 10,

    backgroundColor: '#F18F49',
    marginLeft: 30,
    marginRight: 30,
    justifyContent: 'center',
    borderRadius: 5,
  },
  btntext: {
    textAlign: 'center',
    color: '#fff',
    fontWeight: 'bold',
    fontSize: heightRatio*14,
    letterSpacing: 1,
  },
  footer: {
    letterSpacing: 0.5,
    marginTop: heightRatio*25,
    textAlign: 'center',
    fontSize: heightRatio*12,
  },
  footericon: {
    marginTop: 15,
    backgroundColor: '#E3EEF7',
    elevation: 4,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems:"center",
    // paddingHorizontal: 10,
    width: '45%',
    // marginHorizontal: 110,
    height: 35,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.5,
    shadowRadius: 2,
    borderRadius: 5,
  },
  icon: {
    paddingHorizontal: 5,
  },
  fotter: {
    justifyContent: 'flex-end',
    flex: 1,
    paddingBottom: heightRatio*45,
    alignItems: 'center',
  },
});
export default styles;
