import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  screenlayout: {
    marginTop: 40,
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',

    paddingLeft: 15,
    paddingRight: 15,
  },
  circularcontainer: {
    height: 36,
    width: 36,
    backgroundColor: '#FFFFFF',
    borderWidth: 0.5,
    borderColor: '#FFFFFF',
    borderRadius: 25,
  },
  headertxt: {
    fontWeight: 'bold',
    fontSize: 20,
    color: '#22304A',
  },
  secondheadertxt: {
    fontWeight: 'bold',
    fontSize: 18,
    marginTop: 30,
  },
  headericon: {},
  SubmitButtonStyle: {
      alignSelf:"center",
    //   justifyContent:"center",
    //   alignContent:"center",
    justifyContent: 'space-evenly',
    flexDirection: 'row',
    // marginTop:10,
    paddingTop: 5,
    paddingBottom: 5,
    paddingHorizontal:12,
    marginTop: 10,
    marginLeft: 40,
    // marginRight: 40,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    elevation:4,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.5,
    shadowRadius: 2,
    borderRadius: 20,
    
  },
  phoneno: {
    marginRight: 15,
    marginLeft: 15,
    borderTopColor: '#AFB8C4',
    borderLeftColor: '#E3EEF7',
    borderRightColor: '#E3EEF7',
    borderBottomColor: '#fff',
    borderWidth: 1,
    height: 40,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E3EEF7',
    marginTop: 16,
    marginVertical: 10,
    borderRadius: 10,
    marginBottom: 35,
  },
  searchIcon: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  textinput: {
    flex: 1,
    alignSelf: 'stretch',
    color: '#00FFFF',
  },
  container: {
    marginRight: 15,
    marginTop: 10,
    justifyContent: 'center',
    // width:320,
    borderRadius: 2,
    width: 320,
    height: 140,
    // marginHorizontal:100
  },

  template: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    marginRight: 8,
  },
  templatelast: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
  },
  templateimg: {
    marginTop: 10,
    height: 190,
    width: '100%',
    borderRadius: 5,
  },
  templatetxt: {
    textAlign: 'center',
  },
  SubmitButtonStyle1: {
    height: 50,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    //  marginTop:10,
    paddingTop: 10,
    paddingBottom: 10,
    marginTop: 5,
    backgroundColor: '#fff',
    borderRadius: 5,
  },
  TextStyle: {
      fontSize:16,
    textAlignVertical:"center",
alignSelf:"center",
    textAlign: 'center',
    color: '#000',
    paddingLeft: 10,
  },
});
export default styles;
